services:
  - type: web
    name: jalseva-web
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: MSG91_AUTHKEY
        sync: false
      - key: MSG91_WIDGET_ID
        sync: false
      - key: MSG91_TEMPLATE_ID
        sync: false
